### ISSUE TITLE
BBST

### ISSUE THREAD

**Issue by LisaPassadore** [ckenst/ama#1]
Hi - I am considering taking the BBST courses.  I recently just came across the books, started reading them then realized there are courses attached. I'm wondering if you can tell me if there is a certification for taking the course - something that I can post on my resume or linkedin?

Thanks!

Lisa

**Comment by ckenst** [comment]
Hi @MonstersGeek, sorry for the late reply but I didn't see this. 

If you take the courses and you pass, you'll get a certificate of completion. For the AST courses, it looks something like this: http://www.kenst.com/2013/06/im-a-black-box-test-designer/. Also AST will put your name on their website for reference: https://www.associationforsoftwaretesting.org/training-2/graduates/

**Comment by ckenst** [comment]
I've personally read all of the books and I constantly go through the materials online: http://www.testingeducation.org/BBST/. However there's nothing quite like going through the courses themselves (although they can be way more stressful) because it forces you to learn and learn quickly. 

Let me know if you have any other questions!
