### ISSUE TITLE
Need help on 04 Gateway error page - How to debug the issue /provide logs

### ISSUE THREAD

**Issue by srinivasskc** [ckenst/ama#3]
I am seeing, frequent 504 gateway error page while testing an application. But, it is not reproducible by developers. I find it hard to provide the exact steps. but still tried to produce a video.

is there any way to get to know and provide server (apache) logs to say, when and how it happened ?

**Comment by ckenst** [comment]
500 errors usually mean a server messed up. A 504 typically means one server did not receive a timely response from another. 

A few follow questions:

1. Does this 504 error cause problems within the application you are testing, or are you just concerned about why you might be seeing it? 

2. Where are you testing this application? (In other words do you have it running locally or is it on a separate server?)

3. When you see this error, are you looking at the network traffic / API calls for a specific page? Can you see which calls come first before the 504'd requests? If so what calls are happ

4. What specific call(s) are 504ing? Are they related to the application or are they some 3rd party service?

5. What happens when you ask your developer(s) about potential causes for this call(s) 504ing?

**Comment by ckenst** [comment]
@srinivasskc we're you able to dig any deeper?
